blank_issues_enabled: false
contact_links:
  - name: Обсуждения / Вопросы
    url: https://github.com/st3l1n/awesome_dfir/discussions
    about: Общие вопросы по DFIR, обсуждение методологий и инструментов
